export const SO_GET_RESOURCES = 'SO_GET_RESOURCES';
export const SO_SET_RESOURCES = 'SO_SET_RESOURCES';
export const SO_TRACKING_SEGMENT = 'BLIP_PACKS_EVENTS_TRACK_DATA';
export const SO_NEXT_STEP = 'SO_NEXT_STEP';
export const SO_STEP_BACK = 'SO_STEP_BACK';
