export const SO_GET_RESOURCE = 'SO_GET_RESOURCE';
export const SO_SET_RESOURCES = 'SO_SET_RESOURCES';
export const SO_TRACKING_SEGMENT = 'SO_TRACKING_SEGMENT';
export const SO_MOVE_TO_NEXT_STEP = 'SO_MOVE_TO_NEXT_STEP';
export const SO_MOVE_TO_PREVIOUS_STEP = 'SO_MOVE_TO_PREVIOUS_STEP';
